### PR TITLE
Add override for breaking upstream change around residual trash

### LINKED ISSUE #9: Residual trash not working in 0.4.0
Unfortunately, residual trash doesn't seem to be working here, even after the fixes made in 0.4.0. Example JSON:

```
        "id": 446804,
        "date": "2024-03-08T00:00:00Z",
        "wasteType": {
            "id": 1,
            "code": "RST",
            "title": "Restafval",
            "icon": "restafval",
            "notificationTitle": "Herinnering restafval",
            "notificationText": "Morgen komen we bij je langs om jouw restafval op te halen.",
            "notificationTitleSameDay": "Herinnering restafval",
            "notificationTextSameDay": "Vandaag komen we bij je langs om jouw restafval op te halen."
        },
        "isIrregular": false
    }
```
Looks like we might need to add another line like this: https://github.com/GidoHakvoort/rova/blob/master/rova/rova.py#L83

### PR DESCRIPTION
**Pull request by LukasdeBoer**
So, after https://github.com/GidoHakvoort/rova/pull/7 unfortunately it doesn't seem to be working for residual trash yet. Bio and plastic/PMD works fine but residual is still set to Unknown:
image

I did some digging, and apparently the upstream API refactor brought another change with it for residual trash, example JSON:
```
{
    "id": 446804,
    "date": "2024-03-08T00:00:00Z",
    "wasteType": {
        "id": 1,
        "code": "RST",
        "title": "Restafval",
        "icon": "restafval",
        "notificationTitle": "Herinnering restafval",
        "notificationText": "Morgen komen we bij je langs om jouw restafval op te halen.",
        "notificationTitleSameDay": "Herinnering restafval",
        "notificationTextSameDay": "Vandaag komen we bij je langs om jouw restafval op te halen."
    },
    "isIrregular": false
}
```

This PR makes sure that code `RST` is changed to `RESTAFVAL`. 

Fixes https://github.com/GidoHakvoort/rova/issues/9 and relates to https://github.com/home-assistant/core/issues/110806.

Before:
```
>>> r.get_calendar_items()
[{'GarbageTypeCode': 'RST', 'Date': '2024-03-08T00:00:00'}, {'GarbageTypeCode': 'GFT', 'Date': '2024-03-18T00:00:00'}, {'GarbageTypeCode': 'PMD', 'Date': '2024-03-22T00:00:00'}, {'GarbageTypeCode': 'GFT', 'Date': '2024-03-30T00:00:00'}, {'GarbageTypeCode': 'RST', 'Date': '2024-04-05T00:00:00'}]
```
After:
```>>> r.get_calendar_items()
[{'GarbageTypeCode': 'RESTAFVAL', 'Date': '2024-03-08T00:00:00'}, {'GarbageTypeCode': 'GFT', 'Date': '2024-03-18T00:00:00'}, {'GarbageTypeCode': 'PMD', 'Date': '2024-03-22T00:00:00'}, {'GarbageTypeCode': 'GFT', 'Date': '2024-03-30T00:00:00'}, {'GarbageTypeCode': 'RESTAFVAL', 'Date': '2024-04-05T00:00:00'}]
```

Which lines up with the sensor types defined currently in HA: https://github.com/home-assistant/core/blob/9ac199a8f209b2f843a31fa4a2d00ac18e671f07/homeassistant/components/rova/sensor.py#L47

### CODE REVIEW

**Comment by FerNerd** [comment]
We do not have "RESTAFVAL" in our area anymore ... so i did not check.

While your patch works i would suggest changing:
if garbage_type in {"RST"}:
into
if garbage_type == "RST":

I'ts minor, but i think doing a list check with 1 item is a bit overdone.

**Comment by LukasdeBoer** [comment]
Just wanted to keep consistency, but fair point :)

**Comment by LukasdeBoer** [comment]
Hey @GidoHakvoort What do you think? :)

**Comment by GidoHakvoort** [comment]
@LukasdeBoer and @Smitplaza, thanks for that and same here - no "RESTAFVAL" in our area so missed that - will merge the fix and create a new version and release.

**Comment by LukasdeBoer** [comment]
Just as a confirmation, it's working again in home-assistant dev docker image and should probably be in 2024.3.1:
image

**Pull request merged**
